name: e_hmtii
description: "Aplikasi Manajemen Event Kampus"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  intl: ^0.19.0
  # Firebase
  firebase_core: ^3.6.0
  cloud_firestore: ^5.4.4
  # Media & Upload
  image_picker: ^1.1.2
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/bunga_hmti_logo.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/bunga_hmti_logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
